ckanext/who_afro/assets/css/promoted-plus.css
ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/templates/footer.html
ckanext/who_afro/templates/package/search.html
ckanext/who_afro/templates/package/snippets/promoted_plus.html

More CSS improvements.
Jira ticket is at : https://fjelltopp.atlassian.net/browse/WAC-35

Wac 35 further simple css improvements

---

ckanext/who_afro/helpers.py
ckanext/who_afro/templates/home/snippets/promoted.html
ckanext/who_afro/templates/organization/read.html

This PR includes three small improvements to the UI.  
- Capitalises the featured tag, used to feature datasets on the home page. 
- Updates the home page links to use the iso2 codes
- Puts the org metadata back into the org read page

WAC-26 Small UI improvements

---

ckanext/who_afro/plugin.py
ckanext/who_afro/tests/test_plugin.py

When we are loading some of the values we are trying to load the to object with method `json.loads` which takes argument types: string, bytes or buffer, instead of that we are passing already loaded objects. After this PR we will check if variable that we are passing are string.

WAC-42: Check type before loading to dict.

---

.github/workflows/test.yml
ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/helpers.py
ckanext/who_afro/licenses.json
ckanext/who_afro/plugin.py
ckanext/who_afro/presets.json
ckanext/who_afro/schemas/dataset.yaml
ckanext/who_afro/schemas/indicator.yaml
ckanext/who_afro/schemas/publication.yaml
ckanext/who_afro/schemas/source.yaml
ckanext/who_afro/templates/scheming/display_snippets/language.html
ckanext/who_afro/templates/scheming/display_snippets/multiple_inline.html
ckanext/who_afro/templates/scheming/form_snippets/language.html
ckanext/who_afro/templates/scheming/package/snippets/additional_info.html
ckanext/who_afro/tests/schemas/language_validator.yaml
ckanext/who_afro/tests/schemas/who_license_autofill.yaml
ckanext/who_afro/tests/test_helpers.py
ckanext/who_afro/tests/test_validators.py
ckanext/who_afro/validators.py
dev-requirements.txt
test.ini

Implements a series of metadata changes consistent with what is documented in the [dataset catalogue design](https://docs.google.com/document/d/1U71n8d8VntNti_YawAGaSNzfgw3PmVULWR-ASyT3n9k/edit). 
Specifically associates disclaimers and license details with the available licenses so that these can be shown in page along side the data. 
Also needs: https://github.com/fjelltopp/fjelltopp-infrastructure/pull/237
To see the changes, just create a new "indicator" dataset.  You should find a four part broken down form to enter in a variety of different metadata. Also, view the dataset and you should see a list of tables with metadata structured in a better way.
Matters arising from this PR:
- Do we really need source.yaml and publication.yaml schemas?  I don't think so any more - I think …

WAC-30 Metadata changes

---

ckanext/who_afro/presets.json

Added a new programme to presets so that data related to the Climate Research Unit can be loaded by the ckan_loader.
The issue details can be found within ticket [WAC-102](https://fjelltopp.atlassian.net/browse/WAC-102).

WAC-102 Fix datasets with programmes and languages

---

ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/blueprints/__init__.py
ckanext/who_afro/blueprints/sources.py
ckanext/who_afro/templates/header.html
ckanext/who_afro/templates/home/snippets/featured.html
ckanext/who_afro/templates/home/snippets/promoted.html
ckanext/who_afro/templates/sources/index.html

This PR is for ticket [WAC-112](https://fjelltopp.atlassian.net/browse/WAC-112).
- Made sure the focus underline for each menu item aligns properly with the hero section.
- Aligned the icons and text in the “Find and share critical health data, fast” section in the hero section.
- Changed the “Most viewed/downloaded” subsection title to “Featured data” and subsequently removed the “Featured data” section.
This PR is related:
- [fjelltopp/ckanext-who-afro#38](https://github.com/fjelltopp/ckanext-who-afro/pull/38)
[WAC-112]: https://fjelltopp.atlassian.net/browse/WAC-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WAC-112: [WIP] Small improvements to the homepage redesign

---

ckanext/who_afro/templates/package/search.html
ckanext/who_afro/templates/snippets/facet_list.html

This is essentially the quickest solution to making the sort `select` work. It's pretty tidy but I'm not overly happy about putting the JS in the page - that might change as I add other JS features.

feat: add javascript for updating search params when using the new sort options

---

ckanext/who_afro/templates/admin/base.html

As it says on the tin :canned_food: 
PR #48 removed this snippet but just missed that the admin pages were still using it; this corrects for that.

fix: use the default header for admin pages

---

ckanext/who_afro/assets/css/footer-background.css
ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/templates/footer.html
ckanext/who_afro/templates/home/snippets/footer_background.html
ckanext/who_afro/templates/snippets/subscribe_to_updates.html

This PR, corresponding to ticket [WAC-115](https://fjelltopp.atlassian.net/browse/WAC-115) fixes the missing margin above the WHO logo and repositions the background image to be symmetrical about the x axis.
This is a UI feature so only manual testing could be performed.
Please see the attached picture for acceptance testing.
[WAC-115]: https://fjelltopp.atlassian.net/browse/WAC-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WAC-115: Fix footer margins about WHO logo and reposition the background image on the right side.

---

ckanext/who_afro/assets/css/who-afro.css

It was annoying me that on slow internet the page would load with Serif fonts and then switch to Source Sans when the font was downloaded. This fallbacks to sans-serif so should be less obvious.

feat: make the fallback font sans-serif for cleaner loading

---

ckanext/who_afro/presets.json
ckanext/who_afro/templates/home/snippets/promoted.html

This adds a few additional programmes so we can label the GHDH indicators we are importing with something from Tesfaye's list.
Also updates the home page photo links to incorporate these new programmes.

feat: add more programmes for the GHDH indicators

---

ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/templates/group/read.html
ckanext/who_afro/templates/snippets/facet_list.html

My suggestion for hiding unwanted filters on specific group read pages using CSS. 
The benefit of this solution is that it is easy to modify on a "group by group" basis.

WAC-119 Filter hiding

---

ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/helpers.py
ckanext/who_afro/templates/group/read.html
ckanext/who_afro/templates/snippets/facet_list.html

This PR corresponding to ticket [WAC-119](https://fjelltopp.atlassian.net/browse/WAC-119) redesigns the indicator page according to [Lewis' design](https://www.figma.com/design/n83fVbFXBK01vONu6ApoBb/WHO-AFRO-Data-Hub?node-id=2439-1391&t=83mjEpk3Seaqzcev-0) while taking to have the same design applicable to the `sources` and `publications` pages.
This is the current outcome:
This is UI work so testing was done manually.
A proof of the outcome is attached in the picture above.
[WAC-119]: https://fjelltopp.atlassian.net/browse/WAC-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WAC-119: Indicator list page redesign.

---

ckanext/who_afro/templates/group/read.html
ckanext/who_afro/templates/package/search.html

Previously, the order by field in the dataset and indicators list pages contained only the possibility to order by
relevance, name ascending and name descending.
This PR, corresponding to ticket [WAC-134](https://fjelltopp.atlassian.net/browse/WAC-134), adds the possibility to order by
last modified in the UI. In the code, the possibility to order by popularity is present as a placeholder to eventually replace it
with something like ordering by most downloaded.
Here is the outcome on the indicators list page (which is similar in this regard with the datasets page):
[Screencast from 08-20-2024 03:44:49 AM.webm](https://github.com/user-attachments/assets/e851d972-8ce2-4eff-a892-da31d0592d2e)
Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening …

WAC-134: Review the order by field on datasets and indicators

---

ckanext/who_afro/templates/footer.html

Previously, even if a user is logged in, an "account login" link would be shown at the bottom.
This PR, corresponding to ticket [WAC-133](https://fjelltopp.atlassian.net/browse/WAC-133) makes sure said link is only visible if no user is logged in.
This is the outcome when a user is logged in:
And this is the outcome if a user is *not* logged in:
[WAC-133]: https://fjelltopp.atlassian.net/browse/WAC-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WAC-133: Make sure the 'account login' link in footer is not visible if a user is logged in

---

ckanext/who_afro/templates/footer.html

The about page link was supposed to be moved from the header navigation menu to the footer navigation menu.
This PR, covered by ticket [WAC-132](https://fjelltopp.atlassian.net/browse/WAC-132) makes that happen.
Here is the finalized footer:
[WAC-132]: https://fjelltopp.atlassian.net/browse/WAC-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WAC-132: Added the about page link to the footer.

---

ckanext/who_afro/helpers.py
ckanext/who_afro/plugin.py
ckanext/who_afro/templates/package/overview.html

The client has provided two new indicators and they need no facetting, e.g. they do not have sex disaggregation.
This updates the dashboard to handle the situation where the DIM_SEX field does not exist.
It _should_ be backwards compatible (see Testing below).
Tested live with @A-Souhei - I will manually check all current indicators when this is deployed.

feat: make dashboard work with non-facetted indicators

---

ckanext/who_afro/templates/group/read.html

Hitting "Search" on the indicators page was actually doing a dataset search. This should fix that.

fix: make group search search groups

---

ckanext/who_afro/assets/css/who-afro.css
ckanext/who_afro/templates/package/search.html

This PR fixes two UI issues:
- The search bar was not entirely focusable which can be frustrating to users who may think the field is disabled.
- The title for the "Order by" field was "Really by".
The issues can be found in the "Data" page (and the "Indicators" page for search) as can be seen in the attached picture.

Fix search bar focus and typographical error in datasets page.

---

ckanext/who_afro/templates/group/read.html

When searching the indicators list page, other types of datasets are returned.
This PR fixes that by adding a hidden field to the search query that specifically specifies to search only for the `indicators` group.

[#129] Make sure to return only indicators during search on the indicators list page
