fjelltopp/ckanext-who-afro

- ckanext/who_afro/assets/css/promoted-plus.css
- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/home/layout1.html
- ckanext/who_afro/templates/home/snippets/insights.html
- ckanext/who_afro/templates/home/snippets/promoted.html
- ckanext/who_afro/templates/home/snippets/promoted_plus.html
Ticket is at [https://fjelltopp.atlassian.net/browse/WAC-60?atlOrigin=eyJpIjoiYzk5MGNmOGE3Y2JmNDA0YWI4MmZkNDA0ZWE1MDM2ZDciLCJwIjoiaiJ9](url)
> WAC-60 Act on Lewis' UI feedback

- ckanext/who_afro/assets/css/promoted-plus.css
- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/home/snippets/promoted.html
- ckanext/who_afro/templates/home/snippets/promoted_plus.html
A couple of small UI touchups:
- Getting the promoted plus signs to show and hide appropriately
- Getting the foot copyright statement to blend better with the  background. 
> WAC-60 Small UI touchups

- ckanext/who_afro/assets/css/promoted-plus.css
Improves the positioning of the plus signs in the promoted background. 
> WAC-60 Promoted plus positioning improvements

- ckanext/who_afro/presets.json
Hopefully I've understood this correctly - I just wanted to add VPD to the programmes for the additional demo data I am working on.
Do we need to redeploy for a change like this? Or can it be done manually in the meantime somewhere?
> feat: add VPD to programmes

- .github/workflows/test.yml
- __init__.py
- ckanext/who_afro/tests/test_action_dataset_tag_patch.py
> WAC-47 - Get ckanext-who-afro tests working locally and in github

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/user/edit.html
A temporary fix whilst waiting for the implementation of Lewis user account management workflow.  This PR simply adds a logout button to the manage account page. 
> WAC-74 Add logout button

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/insights/featured.html
Just makes some small formatting improvements to the insights page and updates the dashboard to the latest version. 
> WAC-78 Clean up the insights page appearance

- ckanext/who_afro/assets/css/who-afro.css
Small CSS edits to cleanup data explorer view. 
> WAC-75 CSS cleanup of data explorer view.

- ckanext/who_afro/assets/css/who-afro.css
CSS hotfixes for demo of data previews
> WAC-81 CSS fixes

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/blueprints/__init__.py
- ckanext/who_afro/blueprints/terms.py
- ckanext/who_afro/templates/footer.html
- ckanext/who_afro/templates/home/snippets/disclaimer.html
- ckanext/who_afro/templates/home/terms.html
> WAC-83 add disclaimer to terms and conditions page

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/home/about.html
- ckanext/who_afro/templates/home/snippets/about_text.html
> WAC-82 add relevant about page content

- ckanext/who_afro/schemas/dataset.yaml
Fixes a bug accidentally introduced by #33 and discovered by Ntwali and discussed on Slack.
> fix: add yaml map name

- ckanext/who_afro/presets.json
A mega short one that does what it says on the tin! :canned_food:
Are can't see anywhere where we are translating programme strings - is this right @jonathansberry?
> feat: add IDSR to programmes

- ckanext/who_afro/templates/insights/featured.html
We noticed in Wednesday's call with the client that the featured dashboard on the insights page was not working.
I have had to upgrade our Microsoft Power BI license and regenerate the embed URL. This PR updates that.
> fix: update URL for Power BI dashboard on featured insights

- ckanext/who_afro/presets.json
As it says on the tin :canned_food: 
I will be very happy when the list of programmes stops changing quite so regularly as it's quite a tedious process to get these changes deployed lol.
> feat: add climate to list of programmes

- ckanext/who_afro/templates/insights/featured.html
Basically we had Iko's dashboard with a sharing license but that was old; and Jonathan's dashboard for some reason is not respecting his license... so I copied it into a new license that is both up to date and shareable.....
> fix: point to malaria dashboard that has a license

- ckanext/who_afro/templates/home/snippets/promoted.html
This is obviously not a final solution but it should work with all the data we've included so far in staging?
> feat: make home page photo links work

- ckanext/who_afro/assets/css/who-afro.css
This PR is mostly for reference as I am gonna sudo my way through getting this deployed.
Basically adds the final dashboards and the CSS's as per the client's request.
> fix: make the countries hero container relative positioned so the links are above the background SVG and work

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/footer.html
- ckanext/who_afro/templates/home/snippets/promoted.html
- ckanext/who_afro/templates/insights/featured.html
- ckanext/who_afro/templates/sources/index.html
The client has requested some small cosmetic changes be made for the August launch. 
Note that the indicator page preamble is updated through CKAN as it is part of the CKAN CMS. 
In places the English was really poor, with typos and grammatical errors.  I've done a little proof reading that should have kept all the same sentiment and significant changes.  
> WAC-137 Cosmetic changes requested by the client

- ckanext/who_afro/assets/css/who-afro.css
- ckanext/who_afro/templates/countries/country.html
- ckanext/who_afro/templates/countries/index.html
- ckanext/who_afro/templates/footer.html
- ckanext/who_afro/templates/snippets/facet_list.html
This PR, as per ticket [WAC-136](https://fjelltopp.atlassian.net/browse/WAC-136), improves on the UI so that it looks good on small devices (mobile and tablets).
[WAC-136]: https://fjelltopp.atlassian.net/browse/WAC-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WAC-136: Small improvements to the UI

- ckanext/who_afro/assets/css/who-afro.css
As requested by the client. Reduced the font weight as it was a bit overbearing at this size but the original weight.
> feat: increase nav bar font size

- ckanext/who_afro/templates/home/robots.txt
> fix: prevent robots crawling the site

- ckanext/who_afro/helpers.py
- ckanext/who_afro/plugin.py
- ckanext/who_afro/templates/header.html
Adds a way of easily configuring the login view, to help with using SSO in local and cloud. This PR is part of setting up AFRO SSO. 
> feat: login view switcher
